### ISSUE TITLE
Universal application for server and client

### ISSUE THREAD

**Issue by hung-phan** [elierotenberg/react-prepare#4]
Hi @elierotenberg,

Thanks for creating this library. The approach so far is very matching with my current requirement. I tried redial, react-async, react-async-connect and other libs, but none of them keeps up with the changing spec from react or react-router team that make it so painful to update the library.

I have a small problem with this one. I try to call `prepare` on the server side to pre-render the data, and then load it to the store but the dispatched method is called again in the client side.

For example,

I have a todo component

```javascript
export const Todos = ({ todos, actions }: { todos: TodoType[], actions: Object }) => (
  <div className="container">
    <div className="row">
      <TodosHeader />
      <TodosAdd addTodo={actions.addTodo} />
      <TodosBody
        todos={todos}
        removeTodo={actions.removeTodo}
        completeTodo={actions.completeTodo}
      />
      <TodosFooter />
    </div>
  </div>
);

export const enhance = compose(
  dispatched(
    (props, dispatch) => dispatch(fetchTodos())
  ),
  connect(
    state => ({
      todos: selectors.getTodos(state),
    }),
    dispatch => ({
      actions: bindActionCreators({
        addTodo,
        removeTodo,
        completeTodo,
      }, dispatch),
    })
  ),
  onlyUpdateForKeys(['todos'])
);

export default enhance(Todos);
```

And I tried to use it like this in the server:

```javascript
            const currentRoutes = <RouterContext {...renderProps} />;
            const component = (<App store={store} routes={currentRoutes} />);

            prepare(component)
              .then(() => {
                const prerenderComponent = renderToString(component);
                const prerenderData = store.getState();

                ctx.render(template, {
                  ...parameters,
                  prerenderComponent,
                  prerenderData,
                }).then(resolve).catch(reject);
              });
```

The server is able to call the fetchTodos() and return it to the client, but it triggers another request to server after the client mount again. Is there any way that I could resolve this problem? (I don't want it to be called again in the client if it doesn't need to)

**Comment by hung-phan** [comment]
I think use componentWillMount will solve the issue, what do you think?

**Comment by hung-phan** [comment]
I think the problem is that `componentDidMount` is called again in the client side. `componentWillMount` will solve the problem. What do you think?

**Comment by elierotenberg** [comment]
I'm sorry for the latency, I've been very busy yesterday.
I think you're most likely right. I'm setting up a pet app to troubleshoot this kind of issues. I'll check this and  fix this.

Thanks for your feedback :)

**Comment by hung-phan** [comment]
Thanks @elierotenberg

**Comment by elierotenberg** [comment]
Hello again @hung-phan.

The rationale for `prepare` being called on the client is that the result of dispatching your action may be different between when you prepare server-side and you prepare client-side. In the case of dispatching a fetch action inducing an HTTP request, the response to this request could be different, for example if your server-side state has changed between the server-side rendering time and the client-side rendering time (because of network latency for example). This default behavior ensures that by default, your client-side state remains as up-to-date as necessary.

However, since fetching is performed not directly by the `prepared` decorator, but rather in your redux reducer, it is up to you to implement caching at the redux level if you want to. For example, your reducer could check if the data has already been fetched and perform an actual HTTP request only if it is necessary.

You could also prevent the `dispatched` decorator from firing on `componentDidMount` using `opts.componentDidMount`, but it is not recommended as then, components that you mill mount after the initial rendering will not be correctly prepared.

For a fully working example, see [react-prepare-todo](https://github.com/elierotenberg/react-prepare-todo), and in particular [how the `fetchInto` action creator is defined](https://github.com/elierotenberg/react-prepare-todo/blob/38e2fea6495f69c78bed81e4b2f641abe65abfa0/src/actions.js#L7-L52). By default, it caches data, but this can be overriden by the call site, eg. when the client knows that the server-side data has been modified (such as when an item is [added](https://github.com/elierotenberg/react-prepare-todo/blob/38e2fea6495f69c78bed81e4b2f641abe65abfa0/src/components/UserAddTaskForm.js#L22) or [removed](https://github.com/elierotenberg/react-prepare-todo/blob/38e2fea6495f69c78bed81e4b2f641abe65abfa0/src/components/UserTaskList.js#L16)).

Please feel free to elaborate if you have any further comments :)
